{
 "title": "demo",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": "dev-platform-api,basic-data-service"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache hit",
   "type": "graph",
   "description": "缓存统计",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_cache]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cache" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache_hit_rate",
     "query": "SELECT  sum(hit)/(sum(hit)+sum(miss)) FROM \"rp_30days\".\"cache_hit_rate\" WHERE (\"app\" =~ /^$app$/) AND $timeFilter GROUP BY time(30m), \"cache\" fill(null)",
     "select": [
      [
       { "params": [ "hit" ], "type": "field" },
       { "params": [ "sum(hit)/(sum(hit)+sum(miss))" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "系统运行时间(h)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
   "format": "dateTimeFromNow",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_start_time",
     "query": "SELECT max(\"value\")/1000.0/3600.0 FROM \"rp_30days\".\"process_uptime\" WHERE (\"app\" =~ /^$app$/ AND \"instance-id\" =~ /^$instance$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "系统启动时间",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 9 },
   "format": "dateTimeAsIso",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_start_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "graph",
   "description": "所有的instance情况",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "所有的instance情况",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]]_sys",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]_process",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "request duration tp95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "[[tag_uri]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT  mean(\"mean\") as d FROM \"rp_30days\".\"http_server_requests\" WHERE (\"app\" =~ /^$app$/ AND \"instance-id\" =~ /^$instance$/) AND $timeFilter GROUP BY time(5m), \"uri\" ",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"app\" =~ /^$app$/ ) AND $timeFilter GROUP BY time(1m),  fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "200",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT count(\"count\") FROM \"http_server_requests\" WHERE (\"status\" = '200') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "200" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "500",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT count(\"count\") FROM \"http_server_requests\" WHERE (\"status\" = '200') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "500" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "404",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT count(\"count\") FROM \"http_server_requests\" WHERE (\"status\" = '200') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "404" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "401",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT count(\"count\") FROM \"http_server_requests\" WHERE (\"status\" = '200') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "401" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]]used_[[tag_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "instance-id" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"value\") FROM \"rp_30days\".\"jvm_memory_used\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]commited_[[tag_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "instance-id" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "JVM non heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]]used_[[tag_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "instance-id" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"value\") FROM \"rp_30days\".\"jvm_memory_used\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]commited_[[tag_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "instance-id" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  {
   "title": "JVM Buffer",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]]buffer_total_capacity_[[tag_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "instance-id" ], "type": "tag" }
     ],
     "measurement": "jvm_buffer_total_capacity",
     "query": "SELECT mean(\"value\") FROM \"rp_30days\".\"jvm_memory_used\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]buffer_used_[[tag_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "instance-id" ], "type": "tag" }
     ],
     "measurement": "jvm_buffer_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]][[tag_cause]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "cause" ], "type": "tag" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Thread",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]]current",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_threads_current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]busy",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_threads_busy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]config_max",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_threads_config_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "数据库连接池",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]]connections",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hikaricp_connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]active",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hikaricp_connections_active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]max",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hikaricp_connections_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Thread",
   "type": "graph",
   "description": "当前线程数",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]]daemon",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_daemon",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]live",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_live",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]peak",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance-id]]full_old",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_live_data_size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]allocated",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_memory_allocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    },
    {
     "alias": "[[tag_instance-id]]promoted",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_memory_promoted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" }
     ]
    }
   ]
  },
  { "title": "自定义", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "currentUser duration",
   "type": "graph",
   "description": "获取登录信息api",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "[[col]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT percentile(\"mean\", 95) as tp95, percentile(\"mean\", 90)  as tp90, percentile(\"mean\", 50) as tp50 FROM \"rp_30days\".\"http_server_requests\" WHERE (\"app\" = 'dev-platform-api' AND \"uri\" = '/v1/auth/currentUser') AND $timeFilter GROUP BY time(1m),\"uri\"",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "instance-id", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "uri", "operator": "=", "value": "/v1/auth/currentUser" }
     ]
    }
   ]
  }
 ]
}